### ISSUE TITLE
[Bug]: Disconnected from the server after I upload spectrum

### ISSUE THREAD

**Issue by magagranados** [wincowgerDEV/OpenSpecy-shiny#30] opened 2023-08-14 22:04 UTC
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### What happened?

After I upload a spectrum, I am disconnected from the server and the page requests me to reload. I cannot compare or analyze any spectrum in SPC format.

![image](https://github.com/wincowgerDEV/OpenSpecy-package/assets/142270212/3aca9493-0cc2-4a47-b236-f52956bce96e)

### Steps to reproduce

1. Click "browse"
2. Upload my file in SPC format
3. Choose the preprocessing and identification options. 
...

### Expected behavior

It is expected that after I upload the spectrum, I can preprocess and identify the particle spectrum

### Screenshots or Videos

![image](https://github.com/wincowgerDEV/OpenSpecy-package/assets/142270212/17f7058c-eb4a-4d01-9f18-4de2068aebd8)

**Comment by wincowgerDEV** [comment] 2023-08-21 14:52
Hey @magagranados, thanks for letting us know about this. Can you share the spc file that is causing the issue? It is challenging for us to debug without the file that crashes the server.

**Comment by magagranados** [comment] 2023-08-22 18:53
Hi, here an example
[SPC-2.zip](https://github.com/wincowgerDEV/OpenSpecy-shiny/files/12412021/SPC-2.zip)

**Comment by wincowgerDEV** [comment] 2023-08-23 00:06
Thank you @magagranados. @zsteinmetz, this actually seems like a problem with the package read_any function, getting this error from the function:

```
Error in gsub(rawToChar(replace.nul), "\r\n", log.txt) : 
  'pattern' is invalid
In addition: Warning message:
In gsub(rawToChar(replace.nul), "\r\n", log.txt) :
  unable to translate '<ff>' to a wide string
```

Unfortunately the issue is coming from the ```read.spc()``` from hyperSpec. We will need to rewrite their source code to fix it which will likely take us some time because a lot of these unique file formats are tricky to convert. We should be handling the errors better though instead of letting the app crash and I can work on that for the shiny app sooner rather than later. @magagranados, for now I recommend converting your file into a different format using another software. We have some instructions about how you can use spectragryph to transform your files in our vignette towards the end: https://cran.r-project.org/web/packages/OpenSpecy/vignettes/sop.html

**Comment by zsteinmetz** [comment] 2023-08-23 07:42
> We should be handling the errors better though instead of letting the app crash and I can work on that for the shiny app sooner rather than later.

Agree, @wincowgerDEV. Should we keep the issue here until then?

Instead of trying to completely rewrite their code, I suggest to first approach the hyperSpec maintainers. They have discussed similar issues already; see for instance https://github.com/r-hyperspec/hyperSpec/issues/80 which might soon be fixed with this PR: https://github.com/r-hyperspec/hySpc.read.spc/pull/22

@magagranados would you mind open another issue at https://github.com/r-hyperspec/hySpc.read.spc/issues. If they can fix it, we can benefit from it downstream.

**Comment by wincowgerDEV** [comment] 2023-08-29 16:58
Now catching the incompatible file types with an error message instead of a crash
https://github.com/wincowgerDEV/OpenSpecy-shiny/commit/311a1c4216aa66b0a5ffc86366d3e4056595800c

![image](https://github.com/wincowgerDEV/OpenSpecy-shiny/assets/26821843/e2056982-450a-410f-a087-a429fc606885)

**Closed by wincowgerDEV** 2023-08-29 16:58 UTC
Labels: bug
